version: "3.4"

services:
#  api:
#    image: accounts-manager
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      - LOGS_DIR=/var/log
#    ports:
#      - "8000:8000"
#    volumes:
#      - .:/app
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
